### ISSUE TITLE
Variable naming and organization

### ISSUE THREAD

**Issue by jnwlkr** [BorisMolo/JavaFx#3]
https://github.com/BorisMolo/JavaFx/blob/b0624392c7a8b473b63612fbbfa3634b837b3c41/src/sample/AppController.java#L49

Commented in my fork of this file. Program-wide. Can be cleaned up, made less verbose, in line with convention, and more universally understood

**Comment by jnwlkr** [comment]
Ex: change variable name to startAnimationTimer....

**Comment by BorisMolo** [comment]
Thank you Jen.  
I deleted it))
